//
// CardList.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CardList: Codable {


    /** クレジットカード一覧 */
    public var cards: [Card]

    public init(cards: [Card]) { 
        self.cards = cards
    }


}

