//
// CardForAdd.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CardForAdd: Codable {

    public enum DefaultCard: Int, Codable { 
        case unchecked = 0
        case checked = 1
    }
    /** MDKトークン */
    public var mdkToken: String
    /** 標準カードフラグ  カード情報を明示的に指定せず決済する場合に使用するカードか否かを示すフラグ  0：決済時、カード情報を明示的に指定しない場合に使用されるカードではない  1：決済時、カード情報を明示的に指定しない場合に使用されるカード  */
    public var defaultCard: DefaultCard

    public init(mdkToken: String, defaultCard: DefaultCard) { 
        self.mdkToken = mdkToken
        self.defaultCard = defaultCard
    }

    public enum CodingKeys: String, CodingKey { 
        case mdkToken = "mdk_token"
        case defaultCard = "default_card"
    }


}

