//
// Card.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Card: Codable {

    public enum DefaultCard: Int, Codable { 
        case unchecked = 0
        case checked = 1
    }
    /** [Veritrans応答]  決済サーバーにて付与されたカードIDが返戻されます。  */
    public var cardId: String

    /** [Veritrans応答]  カード番号の先頭6桁と下2桁のみ数字表記され、その他は \&quot;\&quot;*\&quot;\&quot;（アスタリスク）に変換されます。  ハイフンは含まれません。（例\&quot;\&quot;411111********11\&quot;\&quot;）  要求電文の「cardNumber（カード番号）」にてハイフン含みで指定した場合も、ハイフンは含まれずに返戻されます。  */
    public var cardNumber: String

    /** [Veritrans応答]  MM/YY形式 マスクされずに返戻されます。  */
    public var cardExpirationDate: String
    /** [Veritrans応答]  カード情報を明示的に指定せず決済する場合に使用するカードか否かを示すフラグ  0：決済時、カード情報を明示的に指定しない場合に使用されるカードではない  1：決済時、カード情報を明示的に指定しない場合に使用されるカード  */
    public var defaultCard: DefaultCard

    /** カード会社名 */
    public var cardCompany: String?

    public init(cardId: String, cardNumber: String, cardExpirationDate: String, defaultCard: DefaultCard, cardCompany: String?) { 
        self.cardId = cardId
        self.cardNumber = cardNumber
        self.cardExpirationDate = cardExpirationDate
        self.defaultCard = defaultCard
        self.cardCompany = cardCompany
    }

    public enum CodingKeys: String, CodingKey { 
        case cardId = "card_id"
        case cardNumber = "card_number"
        case cardExpirationDate = "card_expiration_date"
        case defaultCard = "default_card"
        case cardCompany = "card_company"
    }


}

