//
// InquireList.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InquireList: Codable {
    
    
    /** (ユーザ向け)お知らせ一覧 */
    public var inquires: [Inquire]
    
    public init(inquires: [Inquire]) {
        self.inquires = inquires
    }
    
    
}

