//
// Payment.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Payment: Codable {

    public enum PaymentStatus: String, Codable { 
        case completed = "completed"
        case error = "error"
        case canceled = "canceled"
    }
    /** 決済ID */
    public var paymentId: Int

    /** チケット番号 */
    public var ticketNumber: String

    /** 決済金額 */
    public var paymentAmount: Int

    /** 決済日時(UTC) */
    public var paymentAt: String
    /** 決済ステータス(completed:完了, error:エラー, canceled:取り消し) */
    public var paymentStatus: PaymentStatus

    /** 決済エラーコード(ベリトランスからの応答) */
    public var paymentErrorCode: String?

    /** 決済エラーメッセージ(ベリトランスからの応答) */
    public var paymentErrorMessage: String?

    /** 決済取り消し日時(UTC) */
    public var cancelAt: String?

    public init(paymentId: Int, ticketNumber: String, paymentAmount: Int, paymentAt: String, paymentStatus: PaymentStatus, paymentErrorCode: String?, paymentErrorMessage: String?, cancelAt: String?) {
        self.paymentId = paymentId
        self.ticketNumber = ticketNumber
        self.paymentAmount = paymentAmount
        self.paymentAt = paymentAt
        self.paymentStatus = paymentStatus
        self.paymentErrorCode = paymentErrorCode
        self.paymentErrorMessage = paymentErrorMessage
        self.cancelAt = cancelAt
    }

    public enum CodingKeys: String, CodingKey { 
        case paymentId = "payment_id"
        case ticketNumber = "ticket_number"
        case paymentAmount = "payment_amount"
        case paymentAt = "payment_at"
        case paymentStatus = "payment_status"
        case paymentErrorCode = "payment_error_code"
        case paymentErrorMessage = "payment_error_message"
        case cancelAt = "cancel_at"
    }


}

