//
// PaymentList.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct PaymentList: Codable {
    /** 全件数 */
    public var total: Int?
    
    /** 1ページに表示する件数(limit) */
    public var perPage: Int?
    
    /** 現在ページ */
    public var currentPage: Int?
    
    /** 最終ページ */
    public var lastPage: Int?
    
    /** 最初のページのURL */
    public var firstPageUrl: String?
    
    /** 最後のページのURL */
    public var lastPageUrl: String?
    
    /** 次のページのURL */
    public var nextPageUrl: String?
    
    /** 前のページのURL */
    public var prevPageUrl: String?
    
    /** ベースURL */
    public var path: String?
    
    /** 項目数from */
    public var from: Int?
    
    /** 項目数to */
    public var to: Int?
    
    /** 決済一覧 */
    public var data: [Payment]
    
    public init(total: Int?, perPage: Int?, currentPage: Int?, lastPage: Int?, firstPageUrl: String?, lastPageUrl: String?, nextPageUrl: String?, prevPageUrl: String?, path: String?, from: Int?, to: Int?, data: [Payment]) {
        self.total = total
        self.perPage = perPage
        self.currentPage = currentPage
        self.lastPage = lastPage
        self.firstPageUrl = firstPageUrl
        self.lastPageUrl = lastPageUrl
        self.nextPageUrl = nextPageUrl
        self.prevPageUrl = prevPageUrl
        self.path = path
        self.from = from
        self.to = to
        self.data = data
    }
    
    public enum CodingKeys: String, CodingKey {
        case total
        case perPage = "per_page"
        case currentPage = "current_page"
        case lastPage = "last_page"
        case firstPageUrl = "first_page_url"
        case lastPageUrl = "last_page_url"
        case nextPageUrl = "next_page_url"
        case prevPageUrl = "prev_page_url"
        case path
        case from
        case to
        case data
    }
}
