//
// StoreInquire.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct StoreInquire: Codable {


    /** お知らせID */
    public var inquireId: Int

    /** お知らせタイトル */
    public var inquireTitle: String

    /** お知らせ内容 */
    public var inquireContents: String

    /** お知らせURL */
    public var inquireUrl: String

    /** お知らせ作成日 */
    public var createdAt: String

    /** 既読 */
    public var read: Bool

    public init(inquireId: Int, inquireTitle: String, inquireContents: String, inquireUrl: String, createdAt: String, read: Bool) { 
        self.inquireId = inquireId
        self.inquireTitle = inquireTitle
        self.inquireContents = inquireContents
        self.inquireUrl = inquireUrl
        self.createdAt = createdAt
        self.read = read
    }

    public enum CodingKeys: String, CodingKey { 
        case inquireId = "inquire_id"
        case inquireTitle = "inquire_title"
        case inquireContents = "inquire_contents"
        case inquireUrl = "inquire_url"
        case createdAt = "created_at"
        case read
    }


}

