//
// TicketForAdd.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TicketForAdd: Codable {

    public enum TicketType: String, Codable { 
        case gift = "gift"
        case _private = "private"
    }    /** チケット種別(gift:通常チケット、private:自分用チケット) */
    public var ticketType: TicketType

    /** チケットの金額 */
    public var ticketAmount: Int?

    /** チケットに表示する文言 */
    public var ticketTitle: String?

    /** チケット有効期限日時 */
    public var ticketExpirationDate: String?

    /** カードID(ベリトランスからの返戻値) */
    public var cardId: String

    public init(ticketType: TicketType, ticketAmount: Int?, ticketTitle: String?, ticketExpirationDate: String?, cardId: String) {
        self.ticketType = ticketType
        self.ticketAmount = ticketAmount
        self.ticketTitle = ticketTitle
        self.ticketExpirationDate = ticketExpirationDate
        self.cardId = cardId
    }

    public enum CodingKeys: String, CodingKey { 
        case ticketType = "ticket_type"
        case ticketAmount = "ticket_amount"
        case ticketTitle = "ticket_title"
        case ticketExpirationDate = "ticket_expiration_date"
        case cardId = "card_id"
    }


}

