//
// TicketListItem.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TicketListItem: Codable {

    public enum TicketType: String, Codable { 
        case gift = "gift"
        case _private = "private"
    }
    public enum TicketStatus: String, Codable { 
        case unused = "unused"
        case used = "used"
        case error = "error"

        static var allValues = [unused, used, error]
    }
    /** チケット番号 */
    public var ticketNumber: String?
    /** チケット種別(gift:通常チケット、private:自分用チケット) */
    public var ticketType: TicketType
    /** チケットステータス(unused:未使用, used:使用済, error:決済エラー) */
    public var ticketStatus: TicketStatus

    /** チケットに表示する文言 */
    public var ticketTitle: String?

    /** チケットの金額 */
    public var ticketAmount: Int?

    /** チケットの有効期限日 */
    public var ticketExpirationDate: String?

    public init(ticketNumber: String?, ticketType: TicketType, ticketStatus: TicketStatus, ticketTitle: String?, ticketAmount: Int?, ticketExpirationDate: String?) {
        self.ticketNumber = ticketNumber
        self.ticketType = ticketType
        self.ticketStatus = ticketStatus
        self.ticketTitle = ticketTitle
        self.ticketAmount = ticketAmount
        self.ticketExpirationDate = ticketExpirationDate
    }

    public enum CodingKeys: String, CodingKey { 
        case ticketNumber = "ticket_number"
        case ticketType = "ticket_type"
        case ticketStatus = "ticket_status"
        case ticketTitle = "ticket_title"
        case ticketAmount = "ticket_amount"
        case ticketExpirationDate = "ticket_expiration_date"
    }


}

