//
// TicketList.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TicketList: Codable {


    /** チケット一覧 */
    public var tickets: [TicketListItem]

    public init(tickets: [TicketListItem]) { 
        self.tickets = tickets
    }


}

